spring:
  datasource:
    url: jdbc:h2:mem:discodeit-test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.test.context: info
    org.springframework.transaction: debug
    com.sprint.mission.discodeit: debug

discodeit:
  repository:
    type: jpa